#!/usr/bin/env python
import os
import io
import time
import re

Import("env")
Import("env_modules")

print("gdqlite module enabled")

gdsqlite_obj = []
env_gdsqlite = env_modules.Clone()
env_gdsqlite.add_source_files(gdsqlite_obj, "src/*.cpp")
env_gdsqlite.add_source_files(gdsqlite_obj, "*.cpp")
env.modules_sources += gdsqlite_obj

sqlite_obj = []
env_sqlite = env_modules.Clone()
env_sqlite.add_source_files(sqlite_obj, "sqlite/sqlite3.c")

env.modules_sources += sqlite_obj
